name: s3sync_provision_template
on:
  schedule:
  - cron:  "*/3 * * * *"
jobs:
  s3-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: shallwefootball/s3-upload-action@master
      name: Upload S3
      id: S3
      with:
        aws_key_id: ${{ secrets.S3_ACCESS }}
        aws_secret_access_key: ${{ secrets.S3_SECRET }}
        aws_bucket: 'pico-cfn'
        source_dir: 'cfn/AWS_Provision_CoreStack/AWS_Provision_CoreStack_content.json'
